name: memorimage_uts_et
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  shared_preferences: ^2.0.15

flutter:
  uses-material-design: true

  assets:
    - assets\images\c-1-1.png
    - assets\images\c-1-2.png
    - assets\images\c-1-3.png
    - assets\images\c-1-4.png
    - assets\images\c-2-1.png
    - assets\images\c-2-2.png
    - assets\images\c-2-3.png
    - assets\images\c-2-4.png
    - assets\images\c-3-1.png
    - assets\images\c-3-2.png
    - assets\images\c-3-3.png
    - assets\images\c-3-4.png
    - assets\images\c-4-1.png
    - assets\images\c-4-2.png
    - assets\images\c-4-3.png
    - assets\images\c-4-4.png
    - assets\images\c-5-1.png
    - assets\images\c-5-2.png
    - assets\images\c-5-3.png
    - assets\images\c-5-4.png
    - assets\images\c-6-1.png
    - assets\images\c-6-2.png
    - assets\images\c-6-3.png
    - assets\images\c-6-4.png
    - assets\images\c-7-1.png
    - assets\images\c-7-2.png
    - assets\images\c-7-3.png
    - assets\images\c-7-4.png
    - assets\images\c-8-1.png
    - assets\images\c-8-2.png
    - assets\images\c-8-3.png
    - assets\images\c-8-4.png
    - assets\images\c-9-1.png
    - assets\images\c-9-2.png
    - assets\images\c-9-3.png
    - assets\images\c-9-4.png
    - assets\images\c-10-1.png
    - assets\images\c-10-2.png
    - assets\images\c-10-3.png
    - assets\images\c-10-4.png
    - assets\images\c-11-1.png
    - assets\images\c-11-2.png
    - assets\images\c-11-3.png
    - assets\images\c-11-4.png
    - assets\images\c-12-1.png
    - assets\images\c-12-2.png
    - assets\images\c-12-3.png
    - assets\images\c-12-4.png
    - assets\images\c-13-1.png
    - assets\images\c-13-2.png
    - assets\images\c-13-3.png
    - assets\images\c-13-4.png
    - assets\images\c-14-1.png
    - assets\images\c-14-2.png
    - assets\images\c-14-3.png
    - assets\images\c-14-4.png
    - assets\images\c-15-1.png
    - assets\images\c-15-2.png
    - assets\images\c-15-3.png
    - assets\images\c-15-4.png
    - assets\images\c-16-1.png
    - assets\images\c-16-2.png
    - assets\images\c-16-3.png
    - assets\images\c-16-4.png
    - assets\images\c-17-1.png
    - assets\images\c-17-2.png
    - assets\images\c-17-3.png
    - assets\images\c-17-4.png
    - assets\images\c-18-1.png
    - assets\images\c-18-2.png
    - assets\images\c-18-3.png
    - assets\images\c-18-4.png
    - assets\images\c-19-1.png
    - assets\images\c-19-2.png
    - assets\images\c-19-3.png
    - assets\images\c-19-4.png
    - assets\images\c-20-1.png
    - assets\images\c-20-2.png
    - assets\images\c-20-3.png
    - assets\images\c-20-4.png
